keys:
  - &blizzard age1a5ddltm2zx8t9vqa2q4yrm6yw53epyafrql8sr8y2vl68w2u5sfql692t3
  - &tundra age1lr2r4pqca2yru6kpjlvlcrwkvjxjesz42qdpewuzwalj0d2qlf2sc6l4es
  - &glaceon age1tsxd04ftgc4hj87m9rwvyp9p3wry6na0xqr3y54ys7696l2m7djs53hdfs
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *blizzard
      - *tundra
