[package]
name = "i3_workspace_monitor"
version = "0.1.0"
edition = "2018"

[profile.release]
strip = "symbols"
opt-level = "z"     
lto = true          
codegen-units = 1

[dependencies]
i3ipc = "0.9"
